spring:
  application:
    name: chatApp
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER_CLASSNAME}
  jpa:
    show-sql: ${JPA_HIBERNATE_SHOW_SQL}
    generate-ddl: ${JPA_HIBERNATE_GENERATE_DDL}
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
      default_schema: ${DATASOURCE_SCHEMA}
    properties:
      hibernate:
        dialect: ${JPA_HIBERNATE_DIALECT}

jwt:
  secret: ${JWT_SECRET}
